import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const DOMAINS = [
  "doubleclick.net",
  "googleadservices.com",
  "googlesyndication.com",
  "googletagservices.com",
  "2mdn.net",
  "googleads.g.doubleclick.net",
  "pagead2.googlesyndication.com",
  "tpc.googlesyndication.com",
  "partner.googleadservices.com",
  "adservice.google.com",
  "google-analytics.com",
  "googleadservices.net",
  "adsensecustomsearchads.com",
  "fundingchoicesmessages.google.com",
  "amazon-adsystem.com",
  "ads-twitter.com",
  "static.ads-twitter.com",
  "ads.linkedin.com",
  "px.ads.linkedin.com",
  "snap.licdn.com",
  "an.facebook.com",
  "pixel.facebook.com",
  "ads.yahoo.com",
  "ads.yap.yahoo.com",
  "adtechus.com",
  "adtech.de",
  "criteo.com",
  "criteo.net",
  "taboola.com",
  "taboolanews.com",
  "outbrain.com",
  "outbrainimg.com",
  "zemanta.com",
  "mgid.com",
  "revcontent.com",
  "content.ad",
  "zergnet.com",
  "nativo.net",
  "postrelease.com",
  "carbonads.com",
  "carbonads.net",
  "buysellads.com",
  "servedby-buysellads.com",
  "ethicalads.io",
  "nitropay.com",
  "adthrive.com",
  "mediavine.com",
  "ezoic.com",
  "ezoic.net",
  "pubmatic.com",
  "rubiconproject.com",
  "openx.net",
  "openx.com",
  "adnxs.com",
  "adsrvr.org",
  "thetradedesk.com",
  "casalemedia.com",
  "indexexchange.com",
  "bidswitch.net",
  "smartadserver.com",
  "adform.net",
  "adition.com",
  "yieldmo.com",
  "media.net",
  "contextweb.com",
  "3lift.com",
  "triplelift.com",
  "sharethrough.com",
  "teads.tv",
  "spotxchange.com",
  "spotx.tv",
  "stickyadstv.com",
  "tremorhub.com",
  "innovid.com",
  "moatads.com",
  "moatpixel.com",
  "doubleverify.com",
  "adsafeprotected.com",
  "iaspromotes.com",
  "serving-sys.com",
  "eyeota.net",
  "krxd.net",
  "bluekai.com",
  "exelator.com",
  "rlcdn.com",
  "agkn.com",
  "turn.com",
  "mathtag.com",
  "demdex.net",
  "everesttech.net",
  "omtrdc.net",
  "adsrvr.org",
  "bidr.io",
  "liadm.com",
  "liveintent.com",
  "crwdcntrl.net",
  "semasio.net",
  "id5-sync.com",
  "sharedid.org",
  "ads.mopub.com",
  "mopub.com",
  "unityads.unity3d.com",
  "applovin.com",
  "applvn.com",
  "ironsrc.com",
  "supersonicads.com",
  "chartboost.com",
  "vungle.com",
  "startapp.com",
  "adcolony.com",
  "pangle.io",
  "pangle-ads.com",
  "smaato.net",
  "smaato.com",
  "inner-active.mobi",
  "tapjoy.com",
  "fyber.com",
  "digitalturbine.com",
  "ads.reddit.com",
  "alb.reddit.com",
  "events.reddit.com",
  "googletagservices.com",
  "scorecardresearch.com",
  "imrworldwide.com",
  "quantserve.com",
  "quantcount.com",
  "chartbeat.com",
  "chartbeat.net",
  "hotjar.com",
  "hotjar.io",
  "clarity.ms",
  "mouseflow.com",
  "fullstory.com",
  "inspectlet.com",
  "crazyegg.com",
  "luckyorange.com",
  "luckyorange.net",
  "segment.io",
  "segment.com",
  "mixpanel.com",
  "amplitude.com",
  "heapanalytics.com",
  "kissmetrics.com",
  "marketo.net",
  "mktoresp.com",
  "hubspot.com",
  "hs-analytics.net",
  "hs-scripts.com",
  "hsadspixel.net",
  "hubspotlinks.com",
  "pardot.com",
  "adroll.com",
  "adotmob.com",
  "rtbhouse.com",
  "creativecdn.com",
  "seedtag.com",
  "justpremium.com",
  "steelhouse.com",
  "steelhousemedia.com",
  "perfectaudience.com",
  "retargetly.com",
  "simpli.fi",
  "stackadapt.com",
  "quantcast.com",
  "quantserve.com",
  "popads.net",
  "popcash.net",
  "propellerads.com",
  "propellerclick.com",
  "adsterra.com",
  "hilltopads.com",
  "clickadu.com",
  "exoclick.com",
  "exosrv.com",
  "realsrv.com",
  "trafficjunky.net",
  "juicyads.com",
  "plugrush.com",
  "adcash.com",
  "adblade.com",
  "adskeeper.com",
  "mgid.com",
  "adk2.com",
  "adk2x.com",
  "bidvertiser.com",
  "chitika.com",
  "infolinks.com",
  "sovrn.com",
  "lijit.com",
  "sonobi.com",
  "sovrn.com",
  "gumgum.com",
  "33across.com",
  "districtm.io",
  "districtm.ca",
  "conversantmedia.com",
  "fastclick.net",
  "mookie1.com",
  "owneriq.net",
  "adscale.de",
  "smartadserver.com",
  "yieldlab.net",
  "emxdgt.com",
  "rhythmone.com",
  "1rx.io",
  "sonobi.com",
  "unrulymedia.com",
  "video.unrulymedia.com",
  "teads.com",
  "lkqd.net",
  "springserve.com",
  "freewheel.tv",
  "fwmrm.net",
  "stickyadstv.com",
  "connatix.com",
  "aniview.com",
  "playbuzz.com",
  "mgid.com",
  "adfox.ru",
  "yandexadexchange.net",
  "an.yandex.ru",
  "ads.vk.com",
  "ad.mail.ru",
  "target.my.com",
  "top.mail.ru",
  "gemius.pl",
  "adocean.pl",
  "adhigh.net",
  "betweendigital.com",
  "otm-r.com",
  "buzzoola.com",
  "hybrid.ai",
  "sape.ru",
  "begun.ru",
  "directadvert.ru",
  "marketgid.com",
  "lentainform.com",
  "relap.io",
  "lentainform.com",
  "gstaticadssl.l.google.com",
  "ad.360yield.com",
  "360yield.com",
  "smartclip.net",
  "adgrx.com",
  "adsymptotic.com",
  "adentifi.com",
  "adsnative.com",
  "sharethrough.com",
  "yieldmo.com",
  "triplelift.com",
  "openx.net",
  "pubmatic.com",
  "rubiconproject.com",
  "casalemedia.com",
  "contextweb.com",
  "bidtheatre.com",
  "admedo.com",
  "adotube.com",
  "advertising.com",
  "atdmt.com",
  "atwola.com",
];

const EXTRA_PATHS = [
  "||youtube.com/pagead",
  "||youtube.com/ptracking",
  "||youtube.com/api/stats/ads",
  "||youtube.com/get_midroll",
  "||youtube.com/pcs/activeview",
  "||facebook.com/tr?",
  "||google.com/pagead/",
  "||google.com/adsense/",
  "||google.com/aclk?",
  "/adsbygoogle.js",
  "/securepubads.",
];

const RESOURCE_TYPES = [
  "main_frame",
  "sub_frame",
  "stylesheet",
  "script",
  "image",
  "font",
  "object",
  "xmlhttprequest",
  "ping",
  "media",
  "websocket",
  "csp_report",
  "other",
];

const SKIP = new Set(["hubspot.com"]);

function unique(list) {
  return [...new Set(list.map((item) => item.trim().toLowerCase()).filter(Boolean))]
    .filter((domain) => !SKIP.has(domain))
    .filter((domain) => domain.includes("."))
    .sort();
}

function chunk(list, size) {
  const groups = [];
  for (let index = 0; index < list.length; index += size) {
    groups.push(list.slice(index, index + size));
  }
  return groups;
}

const domains = unique(DOMAINS);
const rules = [];
let id = 1;

for (const group of chunk(domains, 50)) {
  rules.push({
    id: id++,
    priority: 1,
    action: { type: "block" },
    condition: {
      requestDomains: group,
      resourceTypes: RESOURCE_TYPES,
    },
  });
}

for (const filter of EXTRA_PATHS) {
  rules.push({
    id: id++,
    priority: 2,
    action: { type: "block" },
    condition: {
      urlFilter: filter.startsWith("||") || filter.startsWith("/") ? filter : `||${filter}`,
      resourceTypes: RESOURCE_TYPES.filter((type) => type !== "main_frame"),
    },
  });
}

const out = join(dirname(fileURLToPath(import.meta.url)), "ads.json");
writeFileSync(out, `${JSON.stringify(rules, null, 2)}\n`);
console.log(`Wrote ${rules.length} rules for ${domains.length} domains`);
